#!/bin/sh -e
# checks the health status of a running server
# usage: healthcheck [server url]

URL=${1:-http://localhost:8080/health}

if curl --fail -i "$URL"
then
	echo
	echo 'service is healthy'
else
	echo
	echo 'service is unhealthy'
	exit 1
fi
